apiVersion: v1
kind: ReplicationController
metadata:
  name: <%= projectName %>
  labels:
    name: <%= projectName %>
    tier: <%= tier %>
    type: <%= type %>
spec:
  replicas: <%= replicaCount %>
  selector:
    name: <%= projectName %>
  template:
    metadata:
      labels:
        name: <%= projectName %>
        tier: <%= tier %>
        type: <%= type %>
    spec:
      imagePullSecrets:
        - name: docker-registry-pull-secret
      containers:
        - name: <%= projectName %>
          env:
            - name: PORT
              value: "<%= containerPort %>"
          image: docker.icelandairlabs.com/icelandairlabs/<%= projectName %>:latest
          ports:
            - containerPort: <%= containerPort %>
              name: <%= type %>
